[package]
name = "youtube-img-proxy-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
actix-cors = "0.7.0"
futures = "0.3.30"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.4", features = ["json"] }